### ISSUE TITLE
Relative paths in markdown

### ISSUE THREAD

**Issue by huangwb8** [JabinGP/mdout#1]
Hello~
I want to ask if `mdout` support the relative paths out put. For example, here is a relative path of a .csv file:
```
[GeneSet of hubgenes_kegg.csv](./KEGG/GeneSet of hubgenes_kegg.csv)
```
I hope when outputing pdf/html，the relative path would not be changed to absolute path or identified as text. However, I found `mdout` would condider them as text.
Is that any setting I have to add in the command?
By the way, I use windows cmd to run `mdout`. Thanks!

**Comment by JabinGP** [comment]
### there are two ways to get your code into effect
1. add \ in front of the space such as:
    ```md
    [GeneSet of hubgenes_kegg.csv](./KEGG/GeneSet\ of\ hubgenes_kegg.csv.html)
    ```
2. change your naming style, don‘t use spaces
    ```md
    [GeneSet of hubgenes_kegg.csv](./KEGG/GeneSet_of_hubgenes_kegg.csv.html)
    ```

**Comment by huangwb8** [comment]
Thank you for quickly return~
I found the suggestion of changing the name style is useful for it to be identified as a URL, but an abosolute one~O__O"

from
```
[GeneSet of hubgenes_kegg.csv](./KEGG/GeneSet_of_hubgenes_kegg.csv)
```
to something like 
```
[GeneSet of hubgenes_kegg.csv](file://E/***./KEGG/GeneSet_of_hubgenes_kegg.csv)
```
which is not appreciated because the result would be for other computer instead of mine. It must be the relative path. Are there something important I miss? 

At the same time, I found the `mermaid flowgrath` is not available to be output. Is that means I have to download some alternative settings or something? Or it was just because `mdout` had not supported this function?

By the way ,I use the windows 64 bits version of `mdout`

**Comment by JabinGP** [comment]
@huangwb8 
### For the path problem

I tried it on my 64-bit win10, the markdown source code is

```md
[GeneSet of hubgenes_kegg.csv](./KEGG/GeneSet_of_hubgenes_kegg.html)
```

and the result of `mdout test.md -t html` is a file named `test.html`

```html
...
...
<p><a href="./KEGG/GeneSet_of_hubgenes_kegg.html">GeneSet of hubgenes_kegg.csv</a></p>
...
...
```

The href in the `<a>` tag is `./KEGG/GeneSet_of_hubgenes_kegg.html` , which means that the `<a>` tag points to a relative path instead of an absolute

If I open this html file, I can see the path of this html file is `file:///C:/Users/Fisher/Desktop/test.html`  

And if I click `GeneSet of hubgenes_kegg.csv`, the browser will open this relative path file `./KEGG/GeneSet_of_hubgenes_kegg.html` based on `file:///C:/Users/Fisher/Desktop/test.html` 
 
So the browser will open `file:///C:/Users/Fisher/Desktop/KEGG/GeneSet_of_hubgenes_kegg.html`

The result is in line with expectations, I didn't get an absolute path, so I cann't fix your problem, are you mistakenly thinking that the path in `<a>` tag is an absolute path?  

If you need to use the result for other computer, you should keep the directory structure and copy all relevant content.

### For your need to use `mermaid`  

I am sorry for that because `mdout` is not native support, if you want to use `mermaid`, you may need some knowledge of `html`, `javascript`, `css`, and customize your theme package to implement it.

I am also interested in this features, I will try to add this feature in my free time.

**Comment by huangwb8** [comment]
@JabinGP I think I have got the key point~
I found the feature of path would be different between .html and .pdf output.
If I convert .md to .html, the path would be relative.
If I convert .md to .pdf，the path would be absolute.
I believe it may be some mechanisms different between .html and .pdf themselves, and it doesn't correlated with the `mdout` or other markdown editor.
Thanks for your help~

**Comment by JabinGP** [comment]
@huangwb8 
Interesting phenomenon, thank you for sharing.
